language: d

os:
  - linux
  - osx

# ldc 1.2 to 1.5 don't work on Travis OSX because DUB requires too recent libcurl
matrix:
  exclude:
  - d: ldc-1.2.0
    os: osx
  - d: ldc-1.3.0
    os: osx
  - d: ldc-1.4.0
    os: osx  

d:
 - ldc-1.9.0
 - ldc-1.8.0  
 - ldc-1.7.0  
 - ldc-1.6.0  
 - ldc-1.5.0
 - ldc-1.4.0
 - ldc-1.3.0
 - ldc-1.2.0
 - dmd-beta
 - dmd-2.080.1 
 - dmd-2.079.1  
 - dmd-2.078.2  
 - dmd-2.077.1
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1

script:
  - dub test --compiler=${DC} gfm:core
  - dub test --compiler=${DC} gfm:math
  - dub test --compiler=${DC} gfm:sdl2
  - dub test --compiler=${DC} gfm:opengl
  - dub test --compiler=${DC} gfm:assimp
  - dub test --compiler=${DC} gfm:freeimage
  - dub test --compiler=${DC} gfm:integers
  - dub test --compiler=${DC} gfm:logger
